---
name: Cuppa
description: A testing framework for Java 8
url: http://cuppa.forgerock.org
baseurl: ""
collections:
  docs:
    output: true
defaults:
- scope:
    path: ""
    type: posts
  values:
    layout: blog
    sectionid: blog
- scope:
    path: "docs"
    type: docs
  values:
    layout: docs
    sectionid: docs
permalink: "/blog/:year/:month/:day/:title.html"
paginate: 5
paginate_path: "/blog/page:num/"
exclude:
- Gemfile
- Gemfile.lock
- README.md
- vendor/bundle
kramdown:
  input: GFM
  hard_wrap: false
gems:
- jekyll-paginate
cuppa_version: 1.0.0
surefire_version: 2.19.1
github_url: https://github.com/cuppa-framework/cuppa
